name: This is the reuesable workflow
on: workflow_call
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v7
      - name: Build Project
        run: echo 'Building App...'
